doctrine_mongodb:
    connections:
        default:
            server: '%env(resolve:MONGODB_URL)%'
            options: {}

    default_database: ecoRide
    document_managers:
        default:
            auto_mapping: true