<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Utilisateur extends \App\Entity\Utilisateur implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'avis' => [parent::class, 'avis', null, 16],
        "\0".parent::class."\0".'avisReçus' => [parent::class, 'avisReçus', null, 16],
        "\0".parent::class."\0".'covoiturages' => [parent::class, 'covoiturages', null, 16],
        "\0".parent::class."\0".'covoituragesEnTantQueChauffeur' => [parent::class, 'covoituragesEnTantQueChauffeur', null, 16],
        "\0".parent::class."\0".'credits' => [parent::class, 'credits', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'isActive' => [parent::class, 'isActive', null, 16],
        "\0".parent::class."\0".'isChauffeur' => [parent::class, 'isChauffeur', null, 16],
        "\0".parent::class."\0".'isPassager' => [parent::class, 'isPassager', null, 16],
        "\0".parent::class."\0".'noteMoyenne' => [parent::class, 'noteMoyenne', null, 16],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null, 16],
        "\0".parent::class."\0".'photo' => [parent::class, 'photo', null, 16],
        "\0".parent::class."\0".'preferences' => [parent::class, 'preferences', null, 16],
        "\0".parent::class."\0".'pseudo' => [parent::class, 'pseudo', null, 16],
        "\0".parent::class."\0".'role' => [parent::class, 'role', null, 16],
        "\0".parent::class."\0".'vehicules' => [parent::class, 'vehicules', null, 16],
        'avis' => [parent::class, 'avis', null, 16],
        'avisReçus' => [parent::class, 'avisReçus', null, 16],
        'covoiturages' => [parent::class, 'covoiturages', null, 16],
        'covoituragesEnTantQueChauffeur' => [parent::class, 'covoituragesEnTantQueChauffeur', null, 16],
        'credits' => [parent::class, 'credits', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'isActive' => [parent::class, 'isActive', null, 16],
        'isChauffeur' => [parent::class, 'isChauffeur', null, 16],
        'isPassager' => [parent::class, 'isPassager', null, 16],
        'noteMoyenne' => [parent::class, 'noteMoyenne', null, 16],
        'password' => [parent::class, 'password', null, 16],
        'photo' => [parent::class, 'photo', null, 16],
        'preferences' => [parent::class, 'preferences', null, 16],
        'pseudo' => [parent::class, 'pseudo', null, 16],
        'role' => [parent::class, 'role', null, 16],
        'vehicules' => [parent::class, 'vehicules', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
