<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0LOEe0L\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0LOEe0L/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0LOEe0L.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0LOEe0L\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0LOEe0L\App_KernelDevDebugContainer([
    'container.build_hash' => '0LOEe0L',
    'container.build_id' => 'f74134c0',
    'container.build_time' => 1747814383,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container0LOEe0L');
