<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8mfbCNJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8mfbCNJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8mfbCNJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8mfbCNJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8mfbCNJ\App_KernelDevDebugContainer([
    'container.build_hash' => '8mfbCNJ',
    'container.build_id' => '800a8194',
    'container.build_time' => 1748426644,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container8mfbCNJ');
