<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIhw6m7E\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIhw6m7E/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIhw6m7E.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIhw6m7E\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIhw6m7E\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ihw6m7E',
    'container.build_id' => 'aacf9c49',
    'container.build_time' => 1747809367,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIhw6m7E');
